services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assorelie
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - dokploy-network
    volumes:
      - /home/guillaume/assorelie/data:/var/www/html/data
      - /home/guillaume/assorelie/assets/images/gallery:/var/www/html/assets/images/gallery

networks:
  dokploy-network:
    external: true
